services:
  teams-postgres:
    image: postgres:16-alpine
    container_name: teams-env-postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 2s
      retries: 20

    networks:
      - teams-network


  teams-postgres-migrate:
    image: migrate/migrate:v4.19.1

    depends_on:
      teams-postgres:
        condition: service_healthy

    networks:
      - teams-network

    volumes:
      - ./migrations:/migrations

    entrypoint: ["/migrate"]

    command:
      - -path=/migrations
      - -database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@teams-postgres:5432/${POSTGRES_DB}?sslmode=disable
      - up


networks:
  teams-network:
    driver: bridge


volumes:
  pgdata: